spring.application.name=BasicRESTAPI3
spring.datasource.url=jdbc:postgresql://aws-0-ca-central-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.kldgungbsomqwilwfyge
spring.datasource.password=SebastianTylerJadalynnKarsten
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.session.store-type=none